# Generated by Django 2.1.3 on 2018-12-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testdb',
            table='test',
        ),
    ]
